micronaut:
  application:
    name: calorieapp
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: R9oRMFeBWaxfJIolWPfDWEZHzkLBsWefDtavyWWI
    enabled: false

datasources:
  default:
    url: jdbc:postgresql://127.0.0.1/calorie-app
    username: bhutani
    password: ''
    driverClassName: "org.postgresql.Driver"
    dialect: "postgres"

jpa:
  default:
    packages-to-scan:
      - 'models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

USDA:
  secretkeyid: 'R9oRMFeBWaxfJIolWPfDWEZHzkLBsWefDtavyWWI'