micronaut:
  application:
    name: calorieapp
  server:
    cors:
      enabled: true
    port: 8081
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      logout:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        cookie:
          enabled: false
        generator:
          access-token:
            expiration: 18000 # 5 hours expiration
        signatures:
          secret:
            generator:
              secret: R9oRMFeBWaxfJIolWPfDWEZHzkLBsWefDtavyWWI
    enabled: true
    intercept-url-map:
      - pattern: /
        access:
          - isAnonymous()
      - pattern: /**/resources/**
        access:
          - isAnonymous()
      - pattern: /**/static/**
        access:
          - isAnonymous()
      - pattern: /**/css/**
        access:
          - isAnonymous()
      - pattern: /**/js/**
        access:
          - isAnonymous()
      - pattern: /service-worker.js
        access:
          - isAnonymous()
      - pattern: /manifest.json
        access:
          - isAnonymous()
      - pattern: /*.png
        access:
          - isAnonymous()
      - pattern: /**/favicon.ico/**
        access:
          - isAnonymous()

datasources:
  default:
    url: jdbc:postgresql://127.0.0.1/calorie-app
    username: bhutani
    password: ''
    driverClassName: "org.postgresql.Driver"
    dialect: "postgres"

jpa:
  default:
    packages-to-scan:
      - 'models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

USDA:
  secretkeyid: 'R9oRMFeBWaxfJIolWPfDWEZHzkLBsWefDtavyWWI'